# Generated by Django 3.2.6 on 2021-09-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.IntegerField()),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
